# Generated by Django 6.0 on 2026-01-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('up_coming_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('under_review', 'Under Review'), ('interview', 'Interview'), ('OA_received', 'OA Received'), ('offer_received', 'Offer Received'), ('rejected', 'Rejected')], default='under_review', max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
